language: python

python: 2.7

env:

install:
  - pip install --upgrade pip setuptools tox virtualenv coveralls

script:
  - tox

matrix:
  allow_failures:
    - env: TOXENV=py27-django_trunk
    - env: TOXENV=py32-django_trunk
    - env: TOXENV=py33-django_trunk

after_success: coveralls
